import { Inter } from 'next/font/google';
import './globals.css';
import { FC, Suspense } from 'react';

import type { Metadata } from 'next';

import Header from '@/components/Header';
import StoreProvider from '@/store/components/StoreProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type RootLayoutProps = Readonly<{ children: React.ReactNode }>;

const RootLayout: FC<RootLayoutProps> = ({ children }) => (
  <StoreProvider>
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <main className="flex h-screen w-full justify-center">
          <Suspense fallback={<div>Loading...</div>}>{children}</Suspense>
        </main>
      </body>
    </html>
  </StoreProvider>
);

export default RootLayout;
