import { Montserrat } from 'next/font/google';
import './globals.css';
import 'react-toastify/dist/ReactToastify.css';
import { FC, Suspense } from 'react';

import { Slide, ToastContainer } from 'react-toastify';

import { Providers } from './providers';

import type { Metadata } from 'next';

import Header from '@/components/Header';
import StoreProvider from '@/store/components/StoreProvider';
import StoreWatchers from '@/store/components/StoreWatchers';

const montserrat = Montserrat({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type RootLayoutProps = Readonly<{ children: React.ReactNode }>;

const RootLayout: FC<RootLayoutProps> = ({ children }) => (
  <StoreProvider>
    <html lang="en">
      <body className={montserrat.className}>
        <Providers>
          <Header />

          <main className="flex h-screen w-full justify-center">
            <Suspense fallback={<div>Loading...</div>}>{children}</Suspense>
          </main>
        </Providers>
        <ToastContainer
          position="bottom-center"
          closeButton={false}
          autoClose={4000}
          transition={Slide}
          progressStyle={{ background: 'white' }}
          closeOnClick={false}
          pauseOnHover={false}
          toastClassName="py-0 px-4 bg-white border border-beerus rounded-lg shadow-xl"
          bodyClassName="text-sm text-black p-0 font-normal"
        />
        <StoreWatchers />
      </body>
    </html>
  </StoreProvider>
);

export default RootLayout;
